
INSERT INTO country (co_code, co_name) VALUES ("AF", "Afghanistan");
INSERT INTO country (co_code, co_name) VALUES ("AL", "Albania");
INSERT INTO country (co_code, co_name) VALUES ("DZ", "Algeria");
INSERT INTO country (co_code, co_name) VALUES ("AS", "American Samoa");
INSERT INTO country (co_code, co_name) VALUES ("AD", "Andorra");
INSERT INTO country (co_code, co_name) VALUES ("AO", "Angola");
INSERT INTO country (co_code, co_name) VALUES ("AI", "Anguilla");
INSERT INTO country (co_code, co_name) VALUES ("AQ", "Antarctica");
INSERT INTO country (co_code, co_name) VALUES ("AG", "Antigua and Barbuda");
INSERT INTO country (co_code, co_name) VALUES ("AR", "Argentina");
INSERT INTO country (co_code, co_name) VALUES ("AM", "Armenia");
INSERT INTO country (co_code, co_name) VALUES ("AW", "Aruba");
INSERT INTO country (co_code, co_name) VALUES ("AU", "Australia");
INSERT INTO country (co_code, co_name) VALUES ("AT", "Austria");
INSERT INTO country (co_code, co_name) VALUES ("AZ", "Azerbaijan");
INSERT INTO country (co_code, co_name) VALUES ("BS", "Bahamas");
INSERT INTO country (co_code, co_name) VALUES ("BH", "Bahrain");
INSERT INTO country (co_code, co_name) VALUES ("BD", "Bangladesh");
INSERT INTO country (co_code, co_name) VALUES ("BB", "Barbados");
INSERT INTO country (co_code, co_name) VALUES ("BY", "Belarus");
INSERT INTO country (co_code, co_name) VALUES ("BE", "Belgium");
INSERT INTO country (co_code, co_name) VALUES ("BZ", "Belize");
INSERT INTO country (co_code, co_name) VALUES ("BJ", "Benin");
INSERT INTO country (co_code, co_name) VALUES ("BM", "Bermuda");
INSERT INTO country (co_code, co_name) VALUES ("BT", "Bhutan");
INSERT INTO country (co_code, co_name) VALUES ("BO", "Bolivia, Plurinational State of");
INSERT INTO country (co_code, co_name) VALUES ("BQ", "Bonaire, Sint Eustatius and Saba");
INSERT INTO country (co_code, co_name) VALUES ("BA", "Bosnia and Herzegovina");
INSERT INTO country (co_code, co_name) VALUES ("BW", "Botswana");
INSERT INTO country (co_code, co_name) VALUES ("BV", "Bouvet Island");
INSERT INTO country (co_code, co_name) VALUES ("BR", "Brazil");
INSERT INTO country (co_code, co_name) VALUES ("IO", "British Indian Ocean Territory");
INSERT INTO country (co_code, co_name) VALUES ("BN", "Brunei Darussalam");
INSERT INTO country (co_code, co_name) VALUES ("BG", "Bulgaria");
INSERT INTO country (co_code, co_name) VALUES ("BF", "Burkina Faso");
INSERT INTO country (co_code, co_name) VALUES ("BI", "Burundi");
INSERT INTO country (co_code, co_name) VALUES ("KH", "Cambodia");
INSERT INTO country (co_code, co_name) VALUES ("CM", "Cameroon");
INSERT INTO country (co_code, co_name) VALUES ("CA", "Canada");
INSERT INTO country (co_code, co_name) VALUES ("CV", "Cape Verde");
INSERT INTO country (co_code, co_name) VALUES ("KY", "Cayman Islands");
INSERT INTO country (co_code, co_name) VALUES ("CF", "Central African Republic");
INSERT INTO country (co_code, co_name) VALUES ("TD", "Chad");
INSERT INTO country (co_code, co_name) VALUES ("CL", "Chile");
INSERT INTO country (co_code, co_name) VALUES ("CN", "China");
INSERT INTO country (co_code, co_name) VALUES ("CX", "Christmas Island");
INSERT INTO country (co_code, co_name) VALUES ("CC", "Cocos (Keeling) Islands");
INSERT INTO country (co_code, co_name) VALUES ("CO", "Colombia");
INSERT INTO country (co_code, co_name) VALUES ("KM", "Comoros");
INSERT INTO country (co_code, co_name) VALUES ("CG", "Congo");
INSERT INTO country (co_code, co_name) VALUES ("CD", "Congo, the Democratic Republic of the");
INSERT INTO country (co_code, co_name) VALUES ("CK", "Cook Islands");
INSERT INTO country (co_code, co_name) VALUES ("CR", "Costa Rica");
INSERT INTO country (co_code, co_name) VALUES ("HR", "Croatia");
INSERT INTO country (co_code, co_name) VALUES ("CU", "Cuba");
INSERT INTO country (co_code, co_name) VALUES ("CW", "Curaçao");
INSERT INTO country (co_code, co_name) VALUES ("CY", "Cyprus");
INSERT INTO country (co_code, co_name) VALUES ("CZ", "Czech Republic");
INSERT INTO country (co_code, co_name) VALUES ("CI", "Côte d'Ivoire");
INSERT INTO country (co_code, co_name) VALUES ("DK", "Denmark");
INSERT INTO country (co_code, co_name) VALUES ("DJ", "Djibouti");
INSERT INTO country (co_code, co_name) VALUES ("DM", "Dominica");
INSERT INTO country (co_code, co_name) VALUES ("DO", "Dominican Republic");
INSERT INTO country (co_code, co_name) VALUES ("EC", "Ecuador");
INSERT INTO country (co_code, co_name) VALUES ("EG", "Egypt");
INSERT INTO country (co_code, co_name) VALUES ("SV", "El Salvador");
INSERT INTO country (co_code, co_name) VALUES ("GQ", "Equatorial Guinea");
INSERT INTO country (co_code, co_name) VALUES ("ER", "Eritrea");
INSERT INTO country (co_code, co_name) VALUES ("EE", "Estonia");
INSERT INTO country (co_code, co_name) VALUES ("ET", "Ethiopia");
INSERT INTO country (co_code, co_name) VALUES ("FJ", "Fiji");
INSERT INTO country (co_code, co_name) VALUES ("FI", "Finland");
INSERT INTO country (co_code, co_name) VALUES ("FR", "France");
INSERT INTO country (co_code, co_name) VALUES ("GA", "Gabon");
INSERT INTO country (co_code, co_name) VALUES ("GM", "Gambia");
INSERT INTO country (co_code, co_name) VALUES ("GE", "Georgia");
INSERT INTO country (co_code, co_name) VALUES ("DE", "Germany");
INSERT INTO country (co_code, co_name) VALUES ("GH", "Ghana");
INSERT INTO country (co_code, co_name) VALUES ("GR", "Greece");
INSERT INTO country (co_code, co_name) VALUES ("GD", "Grenada");
INSERT INTO country (co_code, co_name) VALUES ("GT", "Guatemala");
INSERT INTO country (co_code, co_name) VALUES ("GN", "Guinea");
INSERT INTO country (co_code, co_name) VALUES ("GW", "Guinea-Bissau");
INSERT INTO country (co_code, co_name) VALUES ("GY", "Guyana");
INSERT INTO country (co_code, co_name) VALUES ("HT", "Haiti");
INSERT INTO country (co_code, co_name) VALUES ("HN", "Honduras");
INSERT INTO country (co_code, co_name) VALUES ("HK", "Hong Kong");
INSERT INTO country (co_code, co_name) VALUES ("HU", "Hungary");
INSERT INTO country (co_code, co_name) VALUES ("IS", "Iceland");
INSERT INTO country (co_code, co_name) VALUES ("IN", "India");
INSERT INTO country (co_code, co_name) VALUES ("ID", "Indonesia");
INSERT INTO country (co_code, co_name) VALUES ("IR", "Iran, Islamic Republic of");
INSERT INTO country (co_code, co_name) VALUES ("IQ", "Iraq");
INSERT INTO country (co_code, co_name) VALUES ("IE", "Ireland");
INSERT INTO country (co_code, co_name) VALUES ("IL", "Israel");
INSERT INTO country (co_code, co_name) VALUES ("IT", "Italy");
INSERT INTO country (co_code, co_name) VALUES ("JM", "Jamaica");
INSERT INTO country (co_code, co_name) VALUES ("JP", "Japan");
-- Truncated for brevity
